# polygonKey = 'yourpolygonkey'
# host = 'localhost'
# user = 'root'
# password = 'yourpassword'
polygonKey = 'yZXW1pS8NSbdl113puMqllhYyF4KoIbs'
host = 'localhost'
user = 'root'
password = ''
period = 0.2